export default {
  screenMargin: 25,
  buttonActiveOpacity: 0.65,
  headerHeight: 55,
  languages: [
    'English',
    'Japanese',
    'Korean',
    'Spanish',
    'Chinese (Simplified)',
    'Chinese (Traditional)',
    'French',
    'Italian',
    'Czech',
    'Portuguese',
    'Swahili',
  ],
  fromLanguageListTitle: 'Choose your language',
  toLanguageListTitle: 'Choose a new language',
} as const;
